stages:
  - runtime
  - test

.env:
  image: python
  tags:
    - arm64


setup-python-env:
  stage: runtime
  extends:
    - .env
  script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -U pip setuptools wheel
    - pip install -r requirements.txt
  artifacts:
    when: always
    paths:
      - .venv
  
lint-test:
  stage: test
  extends:
    - .env
  script:
    - source .venv/bin/activate
    - black -l100 --check src --diff
  needs:
    - setup-python-env
  
security-test:
  stage: test
  extends:
    - .env
  script:
    - source .venv/bin/activate
    - bandit -r src
  needs:
    - setup-python-env
  
import-test:
  stage: test
  extends:
    - .env
  script:
    - source .venv/bin/activate
    - isort src --check --diff
  needs:
    - setup-python-env
